name: Build & Bundle Size

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
    inputs:
      fail_on_exceed:
        description: 'If true, fail the job when bundle exceeds threshold'
        required: false
        default: 'false'
      bundle_size_threshold:
        description: 'Bundle size threshold in bytes'
        required: false
        default: '1048576'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Set bundle size threshold
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "BUNDLE_SIZE_THRESHOLD=${{ github.event.inputs.bundle_size_threshold }}" >> $GITHUB_ENV
          else
            echo "BUNDLE_SIZE_THRESHOLD=${{ secrets.BUNDLE_SIZE_THRESHOLD || 1048576 }}" >> $GITHUB_ENV
          fi
      - name: Set failure mode
        run: |
          FAIL_ON_EXCEED="false"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.fail_on_exceed }}" == "true" ]]; then
            FAIL_ON_EXCEED="true"
          elif [[ "${{ github.event_name }}" == "push" && ("${{ github.ref }}" == "refs/heads/main" || "${{ github.ref }}" == "refs/heads/master") ]]; then
            FAIL_ON_EXCEED="true"
          fi
          echo "BUNDLE_FAIL_ON_EXCEED=${FAIL_ON_EXCEED}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          npm ci --ignore-scripts
      - name: Build extension
        run: |
          npm run compile
      - name: Check bundle size
        run: node ./scripts/checkBundleSize.js
