name: Dependency Drift

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '*' ]
  schedule:
    - cron: '0 3 * * 1' # weekly check every Monday at 03:00

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dev dependencies
        run: |
          npm ci --ignore-scripts
      - name: Run depcheck
        id: depcheck
        continue-on-error: true
        run: |
          npx depcheck --json > depcheck-report.json
      - name: Upload report
        if: steps.depcheck.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: depcheck-report
          path: depcheck-report.json
